server:
  port: 8090
jwt:
  expiration_time: 360000
  secret: "NsWdPaheBaGjRYuXQ1nTrTVmFRrjFvzONsWdPaheBaGjRYuXQ1nTrTVmFRrjFvzONsWdPaheBaGjRYuXQ1nTrTVmFRrjFvzONsWdPaheBaGjRYuXQ1nTrTVmFRrjFvzONsWdPaheBaGjRYuXQ1nTrTVmFRrjFvzO"
spring:
  application:
    name: ENTER-BE
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  profiles:
    include:
      - db
      - openapi
      - vault
      - kc
    active: local
  servlet:
      multipart:
          max-file-size: 10MB
          max-request-size: 100MB
