spring:
    config:
        activate:
            on-profile: local
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:query;MODE=MySQL;
        username: sa
        password:
    jpa:
        database: H2
        generate-ddl: true
        show-sql: true
        defer-datasource-initialization: true
        properties:
            hibernate:
                format_sql: true
    sql:
        init:
            mode: always
    h2:
        console:
            enabled: true
logging:
    level:
        org.hibernate.sql: debug
---
spring:
    config:
        activate:
            on-profile: test
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:query;MODE=MySQL;
        username: sa
        password:
    jpa:
        database: H2
        generate-ddl: true
        show-sql: true
        defer-datasource-initialization: true
        properties:
            hibernate:
                format_sql: true
    sql:
        init:
            mode: always
    h2:
        console:
            enabled: true
logging:
    level:
        org.hibernate.sql: debug
---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: ${kakao-cloud-database-url}/enter?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
        username: ${kakao-cloud-database-username}
        password: ${kakao-cloud-database-password}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql