spring:
    config:
        activate:
          on-profile: local
    data:
        redis:
            host: localhost
            port: 6379
---
spring:
    config:
        activate:
            on-profile: test
    data:
        redis:
            host: localhost
            port: 6379
---
spring:
    config:
        activate:
            on-profile: dev
    data:
        redis:
            host: ${kakao-cloud-redis-url}
            port: ${kakao-cloud-redis-port}