spring:
    config:
        activate:
            on-profile: local
openapi:
    service:
        title: enter-documentation
        version: 1.0.0
        url: https://localhost:8090
    springdoc:
        api-docs:
            path: /api/v3/api-docs
        swagger-ui:
            path: /api/swagger-ui.html
---
spring:
    config:
        activate:
            on-profile: test
openapi:
    service:
        title: enter-documentation
        version: 1.0.0
        url: https://localhost:8090
    springdoc:
        api-docs:
            path: /api/v3/api-docs
        swagger-ui:
            path: /api/swagger-ui.html
---
spring:
    config:
        activate:
            on-profile: dev
openapi:
    service:
        title: enter-documentation
        version: 1.0.0
        url: https://moaboa.shop
    springdoc:
        api-docs:
            path: /api/v3/api-docs
        swagger-ui:
            path: /api/swagger-ui.html
