management:
    endpoints:
        enabled-by-default: false
        web:
          exposure:
              include: "*"
    endpoint:
        health:
          enabled: true
          show-details: always
        prometheus:
            enabled: true
        metrics:
            enabled: true
spring:
    config:
        activate:
            on-profile: dev
logging:
    file:
        name: /var/log/spring/application.log