spring:
    config:
        activate:
            on-profile: local
license:
    client:
        id: ${license-client-id}
        secret: ${license-client-secret}
    public:
        key: ${license-public-key}
    url:
        demo: ${license-url-demo}