spring:
    config:
        activate:
            on-profile: local
    cloud:
        vault:
            enabled: false
---

spring:
    config:
        activate:
            on-profile: test
    cloud:
        vault:
            enabled: false
---
spring:
    config:
        activate:
            on-profile: dev
        import:
            - vault://secret/database
            - vault://secret/kc
            - vault://secret/security
            - vault://secret/license
    cloud:
        vault:
            token: ${dev-vault-token}
            scheme: http
            host: ${dev-vault-host}
            port: ${dev-vault-port}
            kv:
                enabled: true
                backend: secret
                profiles: