spring:
    config:
        activate:
            on-profile: local
kakao:
    cloud:
        access: ${kakao-cloud-access}
        secret: ${kakao-cloud-secret}
        region: ${kakao-cloud-region}
        bucket:
            name: ${kakao-cloud-bucket-name}
            endpoint: ${kakao-cloud-bucket-endpoint}
        cdn:
            endpoint: ${kakao-cloud-cdn-endpoint}
---
spring:
    config:
        activate:
            on-profile: test
kakao:
    cloud:
        access: test
        secret: test
        region: test
        bucket:
            name: test
            endpoint: test
        cdn:
            endpoint: test
---
spring:
    config:
        activate:
            on-profile: dev
kakao:
    cloud:
        access: ${kakao-cloud-access}
        secret: ${kakao-cloud-secret}
        region: ${kakao-cloud-region}
        bucket:
            name: ${kakao-cloud-bucket-name}
            endpoint: ${kakao-cloud-bucket-endpoint}
        cdn:
            endpoint: ${kakao-cloud-cdn-endpoint}