server:
  port: 8090

spring:
  application:
    name: ENTER-BE
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  profiles:
    include:
      - db
      - openapi
      - vault
      - kc
      - jwt
      - email
      - licenseapi
      - monitoring
      - quartz
      - redis
      - aes
    active: local
  servlet:
      multipart:
          max-file-size: 10MB
          max-request-size: 100MB
